### ISSUE TITLE
🚀 Feature: avoid omission for new lines

### ISSUE THREAD

**Issue by sosukesuzuki** [JoshuaKGoldberg/console-fail-test#192]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/console-fail-test/issues?q=is%3Aissue+label%3A%22type%3A+feature%22) and found none that matched my issue.

### Overview

For example, typescript-eslint warns like below:

```
=============
    
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
    
You may find that it works just fine, or you may not.
    
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <5.0.0
    
YOUR TYPESCRIPT VERSION: 5.0.1-rc
    
Please only submit bug reports when using the officially supported version.

=============
```

In this case, if tests are failed for the above reason, `console-fail-test` prints like below:

```
Oh no! Your test called the following console method:
  * log (1 call)
    > Call 0: "=============...
```

I couldn't understand what happened from the message.

So I think it is better to print all printed value that includes new lines characters.

**Comment by JoshuaKGoldberg** [comment]
Makes sense, thanks for filing! I'd even consider this a bug, not a feature.
